maybe this works on macos

diff --git a/dev/pre-commit b/dev/pre-commit
--- a/dev/pre-commit
+++ b/dev/pre-commit
@@ -1,33 +1,48 @@
 #!/bin/bash
 
-echo $'\n\tStarting Pre-Commit ESLint validation script'
+RED_BG=$'\e[41m'
+GREEN_BG=$'\e[42m'
+BLUE_TXT=$'\e[36m'
+RED_TXT=$'\e[31m'
+CLR=$'\e[0m'
+
+printf "\n\t${BLUE_TXT}Starting pre-commit ESLint JS/JSX validation script${CLR}\n"
 
 STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".jsx\{0,1\}$")
 
-if [[ "$STAGED_FILES" = "" ]]; then
-  echo $'\n\t\e[0;36mNo files are currently staged\e[0m'
+if [[ "${STAGED_FILES}" == "" ]]; then
+  printf "\n\t${BLUE_TXT}No JS or JSX files are currently staged${CLR}\n"
+  printf "\n\t${GREEN_BG}COMMIT VALIDATED${CLR}\n"
+  echo
   exit 0
 fi
 
 PASS=true
+FILES_TO_FIX=()
 
-for FILE in $STAGED_FILES; do
-  npx eslint "$FILE"
+for FILE in ${STAGED_FILES}; do
+  npx eslint ${FILE}
   if [[ "$?" == 0 ]]; then
-    echo $'\t\e[32mESLint Passed: $FILE\e[0m'
+    printf "\t${GREEN_BG}ESLint Passed: ${FILE}${CLR}"
   else
-    echo $'\t\e[41mESLint Failed: $FILE\e[0m'
+    printf "\t${RED_BG}ESLint Failed: ${FILE}${CLR}"
+    FILES_TO_FIX+=("${FILE}")
     PASS=false
   fi
 done
 
-echo $'\nJavascript validation completed!\n'
+printf "\n\n\t${BLUE_TXT}Javascript validation completed!${CLR}\n"
 
-if ! $PASS; then
-  echo $'\n\t\e[41mCOMMIT FAILED:\e[0m Your commit contains files that makes ESLint grumpy.\nPlease fix the ESLint errors and try again.\n'
+if ! ${PASS}; then
+  printf "\n\t${RED_BG}COMMIT FAILED:${CLR} Your commit contains files that makes ESLint grumpy.\n\tPlease correct these following files:\n\n"
+  for FILE in ${FILES_TO_FIX[@]}; do
+    printf "\t> ${RED_TXT}${FILE}${CLR}\n"
+  done
+  echo
   exit 1
 else
-  echo $'\n\t\e[42mCOMMIT SUCCEEDED\e[0m\n'
+  printf "\n\t${GREEN_BG}COMMIT VALIDATED${CLR}\n"
+  echo
 fi
 
 exit $?
